<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Eg55zFH' shared service.

return $this->privates['.service_locator.Eg55zFH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\MuseumSearchController::index' => ['privates', '.service_locator.ASezHR8', 'get_ServiceLocator_ASezHR8Service.php', true],
    'App\\Controller\\MuseumSearchController::museumCreate' => ['privates', '.service_locator.L3sV_kn', 'get_ServiceLocator_L3sVKnService.php', true],
    'App\\Controller\\MuseumSearchController::museumDelete' => ['privates', '.service_locator..xsEcvu', 'get_ServiceLocator__XsEcvuService.php', true],
    'App\\Controller\\MuseumSearchController::museumEdit' => ['privates', '.service_locator.L3sV_kn', 'get_ServiceLocator_L3sVKnService.php', true],
    'App\\Controller\\MuseumSearchController::show' => ['privates', '.service_locator.qUk3ozV', 'get_ServiceLocator_QUk3ozVService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\MuseumSearchController:index' => ['privates', '.service_locator.ASezHR8', 'get_ServiceLocator_ASezHR8Service.php', true],
    'App\\Controller\\MuseumSearchController:museumCreate' => ['privates', '.service_locator.L3sV_kn', 'get_ServiceLocator_L3sVKnService.php', true],
    'App\\Controller\\MuseumSearchController:museumDelete' => ['privates', '.service_locator..xsEcvu', 'get_ServiceLocator__XsEcvuService.php', true],
    'App\\Controller\\MuseumSearchController:museumEdit' => ['privates', '.service_locator.L3sV_kn', 'get_ServiceLocator_L3sVKnService.php', true],
    'App\\Controller\\MuseumSearchController:show' => ['privates', '.service_locator.qUk3ozV', 'get_ServiceLocator_QUk3ozVService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
], [
    'App\\Controller\\MuseumSearchController::index' => '?',
    'App\\Controller\\MuseumSearchController::museumCreate' => '?',
    'App\\Controller\\MuseumSearchController::museumDelete' => '?',
    'App\\Controller\\MuseumSearchController::museumEdit' => '?',
    'App\\Controller\\MuseumSearchController::show' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\MuseumSearchController:index' => '?',
    'App\\Controller\\MuseumSearchController:museumCreate' => '?',
    'App\\Controller\\MuseumSearchController:museumDelete' => '?',
    'App\\Controller\\MuseumSearchController:museumEdit' => '?',
    'App\\Controller\\MuseumSearchController:show' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
]);
