<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2T5z8RC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2T5z8RC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2T5z8RC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2T5z8RC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2T5z8RC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2T5z8RC',
    'container.build_id' => '80a26334',
    'container.build_time' => 1567165151,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2T5z8RC');
