<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNX85IdK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNX85IdK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNX85IdK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNX85IdK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNX85IdK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NX85IdK',
    'container.build_id' => '226e7a0a',
    'container.build_time' => 1567703336,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNX85IdK');
