<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU72v0lh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU72v0lh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU72v0lh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU72v0lh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU72v0lh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U72v0lh',
    'container.build_id' => '8238892f',
    'container.build_time' => 1568715868,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU72v0lh');
