<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.e8WTtPS' shared service.

return $this->privates['.service_locator.e8WTtPS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\MuseumSearchController::formMuseum' => ['privates', '.service_locator.L3sV_kn', 'get_ServiceLocator_L3sVKnService.php', true],
    'App\\Controller\\MuseumSearchController::index' => ['privates', '.service_locator.h_R3xFD', 'get_ServiceLocator_HR3xFDService.php', true],
    'App\\Controller\\MuseumSearchController::show' => ['privates', '.service_locator.qUk3ozV', 'get_ServiceLocator_QUk3ozVService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\MuseumSearchController:formMuseum' => ['privates', '.service_locator.L3sV_kn', 'get_ServiceLocator_L3sVKnService.php', true],
    'App\\Controller\\MuseumSearchController:index' => ['privates', '.service_locator.h_R3xFD', 'get_ServiceLocator_HR3xFDService.php', true],
    'App\\Controller\\MuseumSearchController:show' => ['privates', '.service_locator.qUk3ozV', 'get_ServiceLocator_QUk3ozVService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
], [
    'App\\Controller\\MuseumSearchController::formMuseum' => '?',
    'App\\Controller\\MuseumSearchController::index' => '?',
    'App\\Controller\\MuseumSearchController::show' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\MuseumSearchController:formMuseum' => '?',
    'App\\Controller\\MuseumSearchController:index' => '?',
    'App\\Controller\\MuseumSearchController:show' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
]);
